routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@homePage')->name('pages.home');
Route::get('news', 'PagesController@newsPage')->name('pages.news');
Route::get('news/category/{category}', 'PagesController@newsPage')->name('pages.categoryNews');
Route::get('news/{news}', 'PagesController@newsDetailPage')->name('pages.detailNews');

Route::get('contact', 'PagesController@contactPage')->name('pages.contact');
Route::post('store-contact', 'PagesController@storeContact')->name('pages.storeContact');

//User login & logout
Route::get('login', 'admin\UsersController@login')->name('login');
Route::post('authenticate', 'admin\UsersController@authenticate')->name('authenticate');
Route::get('logout', 'admin\UsersController@logout')->name('logout');


Route::group(['prefix'=>'admin-panel', 'middleware'=>'auth'], function (){
    //News
    Route::post('news/select', 'admin\NewsController@selectNews')->name('news.list');
    Route::post('news/is-published/{id}', 'admin\NewsController@isPublished')->name('news.isPublished');
    Route::post('news/is-must-read/{id}', 'admin\NewsController@isMustRead')->name('news.isMustRead');
    Route::resource('news', 'admin\NewsController');

    //Category
    Route::post('category/select', 'admin\NewsCategoryController@selectCategories')->name('category.list');
    Route::resource('category', 'admin\NewsCategoryController');

    //User
    Route::get('user/profile', 'admin\UsersController@profile')->name('user.profile');
    Route::post('user/update/{user}', 'admin\UsersController@update')->name('user.update');
    Route::post('user/change-password/{user}', 'admin\UsersController@changePassword')->name('user.change-password');

    //Contact
    Route::get('contact', 'admin\ContactController@index')->name('contact.index');
    Route::post('contact/select', 'admin\ContactController@selectContact')->name('contact.list');
    Route::post('contact/is-viewed/{id}', 'admin\ContactController@isViewed')->name('contact.isViewed');

    Route::delete('contact/{id}', 'admin\ContactController@destroy')->name('contact.destroy');



});

app/NewsCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NewsCategory extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'categories';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'alias'];

    /**
     * Set primary key for table.
     *
     * @var string
     */
    protected $primaryKey = 'id_cat';

}

app/Http/Controllers/admin/NewsCategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Helpers\MyUrl;
use App\Http\Controllers\Controller;
use App\NewsCategory;
use Illuminate\Http\Request;

class NewsCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin/news-category/index', ['activePage' => 'categories']);

    }

    /**
     * @return JSON for Data table with all records
     */
    public function selectCategories()
    {
        $query = NewsCategory::select('id_cat', 'name', 'created_at');

        return datatables($query)
            ->order(function ($query) {
                $columns = [
                    0 => 'name',
                    1 => 'created_at'
                ];

                $dir = request()->order[0]['dir'];
                $col =  $columns[intval(request()->order[0]['column'])];

                $query->orderBy($col, $dir);
            })

            ->rawColumns(['actions', 'date', 'name'])
            ->addColumn('actions', 'admin/news-category/partial/actions')

            ->addColumn('date', function($query){
                return date('d.m.Y', strtotime($query->created_at));
            })

            ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/news-category/form', ['activePage' => 'categories']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, ['name'=> 'required']);

        $input = $request->all();
        $input['alias'] = MyUrl::makeSlugs($input['name']);

        $category = new NewsCategory();
        $category->fill($input);
        $category->save();

        return response()->json([
            'status'  => 'success',
            'message' => "Category was added successfully"
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin/news-category/form', NewsCategory::findOrFail($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, ['name'=> 'required']);

        $input = $request->all();
        $input['alias'] = MyUrl::makeSlugs($input['name']);

        $category = NewsCategory::findOrFail($id);;
        $category->fill($input);
        $category->update();

        return response()->json([
            'status'  => 'success',
            'message' => "Category was added updated"
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = NewsCategory::findOrFail($id);
        $category->delete();

        return response()->json([
            'status'  => 'success',
            'message' => 'The category has been deleted',
        ], 200);
    }
}

resources/views/admin/news-category/form.blade.php
<div class="card card-primary modal-form" style="padding: 0!important; width: 400px">
    <div class="card-header" style="border-radius: 0!important;">
        <h3 class="card-title">{{!empty($id_cat) ? 'Edit' : 'Add' }} category</h3>
    </div>

    <form id="category-form" action="{{!empty($id_cat) ? route('category.update', ['category' => $id_cat]) : route('category.store')}}" method="post">

        @if (!empty($id_cat))
            <input type="hidden" name="_method" value="PUT">
        @endif

        <div class="card-body">
            <div class="form-group">
                <label for="name">Category name</label>
                <input type="text" class="form-control validate[required]" id="name" name="name" value="{{!empty($name) ? $name : ''}}" placeholder="Category name:">
            </div>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>


<script>
    var validation = $("#category-form").validationEngine('attach',{promptPosition : "bottomLeft", maxErrorsPerField: 1});

    $('#category-form').on('submit', function (e) {
        e.preventDefault();
        if(!validation.validationEngine('validate')){
            return false;
        }

        $.ajax({
            url : $(this).attr('action'),
            type : 'POST',
            dataType : 'JSON',
            data : $(this).serialize(),
            success : function(response){
                sweetalert('success', 'Success', response.message);
                $.fancybox.close();
                dt.draw(false);
            },
            error: function (error) {
                onSaveRequestError(error);
            }
        });
    });

</script>

resources/views/admin/news-category/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content-wrapper" style="min-height: 1015.13px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Categories</h1>
                    </div>

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">List of all categories</h3>

                            <div class="card-tools">
                                <a data-fancybox data-type="ajax" data-src="{{route('category.create')}}" href="javascript:;" class="btn btn-success"><i class="fas fa-plus"></i> Add category</a>
                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4"><div class="row"><div class="col-sm-12 col-md-6"></div><div class="col-sm-12 col-md-6"></div></div><div class="row"><div class="col-sm-12">
                                        <table id="categories-table" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                            <thead>
                                            <tr role="row">
                                                <th>Name</th>
                                                <th>Date add</th>
                                                <th>Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            </tbody>

                                        </table>
                                    </div>
                                    <!-- /.card-body -->
                                </div>
                                <!-- /.card -->

                                <!-- /.card -->
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

    <script>
        var dt;

        $(document).ready(function() {

            dt = $('#categories-table').DataTable( {
                "processing": true,
                "serverSide": true,
                "searching": true,
                "autoWidth": false,
                responsive: true,
                stateSave: true,
                "order": [ 1, 'desc' ],
                "columnDefs": [
                    {"orderable": true, "targets": 0},
                    {"orderable": true, className: "ta-c w-100", "targets": 1},
                    {"orderable": false, className: "ta-c w-200", "targets": 2},
                ],
                "columns": [
                    { "data": "name"},
                    { "data": "date" },
                    { "data": "actions" },
                ],
                "ajax": {
                    url: "{{route('category.list')}}",
                    type: 'POST',
                }

            });
        });
    </script>

@endsection