routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@homePage')->name('pages.home');
Route::get('news', 'PagesController@newsPage')->name('pages.news');
Route::get('news/category/{category}', 'PagesController@newsPage')->name('pages.categoryNews');
Route::get('news/{news}', 'PagesController@newsDetailPage')->name('pages.detailNews');

Route::get('contact', 'PagesController@contactPage')->name('pages.contact');
Route::post('store-contact', 'PagesController@storeContact')->name('pages.storeContact');

//User login & logout
Route::get('login', 'admin\UsersController@login')->name('login');
Route::post('authenticate', 'admin\UsersController@authenticate')->name('authenticate');
Route::get('logout', 'admin\UsersController@logout')->name('logout');


Route::group(['prefix'=>'admin-panel', 'middleware'=>'auth'], function (){
    //News
    Route::post('news/select', 'admin\NewsController@selectNews')->name('news.list');
    Route::post('news/is-published/{id}', 'admin\NewsController@isPublished')->name('news.isPublished');
    Route::post('news/is-must-read/{id}', 'admin\NewsController@isMustRead')->name('news.isMustRead');
    Route::resource('news', 'admin\NewsController');

    //Category
    Route::post('category/select', 'admin\NewsCategoryController@selectCategories')->name('category.list');
    Route::resource('category', 'admin\NewsCategoryController');

    //User
    Route::get('user/profile', 'admin\UsersController@profile')->name('user.profile');
    Route::post('user/update/{user}', 'admin\UsersController@update')->name('user.update');
    Route::post('user/change-password/{user}', 'admin\UsersController@changePassword')->name('user.change-password');

    //Contact
    Route::get('contact', 'admin\ContactController@index')->name('contact.index');
    Route::post('contact/select', 'admin\ContactController@selectContact')->name('contact.list');
    Route::post('contact/is-viewed/{id}', 'admin\ContactController@isViewed')->name('contact.isViewed');

    Route::delete('contact/{id}', 'admin\ContactController@destroy')->name('contact.destroy');



});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Znews | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="{{asset('images/favicon.ico')}}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('AdminLTE/dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">

    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">

    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/croppie/croppie.css')}}" />

    <link rel="stylesheet" href="{{asset('plugins/fancybox/dist/jquery.fancybox.min.css')}}" />
    <link rel="stylesheet" href="{{asset('css/admin-css.css')}}" />
    <link rel="stylesheet" href="{{asset('css/sizes.css')}}" />


    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link href="{{asset('plugins/Validation-Engine/validationEngine.jquery.css')}}" rel="stylesheet" type="text/css" />
    <!-- jQuery -->
    <script src="{{asset('AdminLTE/plugins/jquery/jquery.min.js')}}"></script>

    <script src="{{asset('AdminLTE/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>

</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="#" class="brand-link">
            <img src="{{asset('AdminLTE/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light"><strong>Z</strong>NEWS</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">

                    @if (!empty(Auth::user()->avatar))
                        <img src="{{asset('images/users') . '/' . Auth::user()->avatar}}" class="img-circle elevation-2" alt="{{Auth::user()->surname . ' ' . Auth::user()->name}}">
                    @else
                        <img src="{{asset('images/no_avatar.png')}}" class="img-circle elevation-2" alt="{{Auth::user()->surname . ' ' . Auth::user()->name}}">
                    @endif


                </div>
                <div class="info">
                    <a href="#" class="d-block">{{Auth::user()->surname . ' ' . Auth::user()->name}}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                    <li class="nav-item">
                        <a href="{{route('category.index')}}" class="nav-link {{!empty($activePage) && $activePage == 'categories' ? 'active' : ''}}">
                            <i class="nav-icon fas fa-list"></i>
                            <p>Categories</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{{route('news.index')}}" class="nav-link {{!empty($activePage) && $activePage == 'news' ? 'active' : ''}}">
                            <i class="nav-icon far fa-newspaper"></i>
                            <p>News</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{{route('contact.index')}}" class="nav-link {{!empty($activePage) && $activePage == 'contact' ? 'active' : ''}}">
                            <i class="nav-icon fas fa-envelope"></i>
                            <p>Contact message</p>
                        </a>
                    </li>

                    <li class="nav-header">USER</li>

                    <li class="nav-item">
                        <a href="{{route('user.profile')}}" class="nav-link {{!empty($activePage) && $activePage == 'profile' ? 'active' : ''}}">
                            <i class="nav-icon far fa-user"></i>
                            <p>Profile</p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="logout" data-text="Do you want to leave the admin-panel?" data-url="{{route('logout')}}">
                            <i class="nav-icon fas fa-arrow-alt-circle-left"></i>
                            <p>Logout</p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>


    @yield('content')


    <!-- /.content-wrapper -->
            <footer class="main-footer">
                <strong>Copyright &copy; 2014-2019<a href="http://adminlte.io">AdminLTE.io</a>.</strong>
                All rights reserved.
                <div class="float-right d-none d-sm-inline-block">
                    <b>Version</b> 3.0.0-rc.1
                </div>
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Control sidebar content goes here -->
            </aside>
            <!-- /.control-sidebar -->
        </div>
        <!-- ./wrapper -->

        <!-- jQuery UI 1.11.4 -->
        <script src="{{asset('AdminLTE/plugins/jquery-ui/jquery-ui.min.js   ')}}"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
            $.widget.bridge('uibutton', $.ui.button)
        </script>
        <!-- Bootstrap 4 -->
        <script src="{{asset('AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

        <script src="{{asset('AdminLTE/plugins/sweetalert2/sweetalert2.min.js')}}"></script>

        <script src="{{asset('AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
        <!-- AdminLTE App -->
        <script src="{{asset('AdminLTE/dist/js/adminlte.js')}}"></script>


        <script src="{{asset('plugins/Validation-Engine/jquery.validationEngine.js')}}"></script>
        <script src="{{asset('plugins/Validation-Engine/jquery.validationEngine-en.js')}}"></script>

        <script src="{{asset('AdminLTE/plugins/croppie/croppie.js')}}"></script>
        <script src="{{asset('plugins/fancybox/dist/jquery.fancybox.min.js')}}"></script>
        <script src="{{asset('js/admin-js.js')}}"></script>

    </body>
</html>

resources/views/layouts/paginate.blade.php
@if ($paginator->hasPages())
    <ul class="page-numbers">
        <!-- Previous Page Link -->
        @if (!$paginator->onFirstPage())
            <li class="prev page-numbers"><a href="{{ $paginator->previousPageUrl() }}" rel="prev">Previous</a></li>
        @endif

        <!-- Pagination Elements -->
        @foreach ($elements as $element)
        <!-- "Three Dots" Separator -->
            @if (is_string($element))
                <li class="disabled"><span>{{ $element }}</span></li>
            @endif

        <!-- Array Of Links -->
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                        <li><span class="page-numbers current">{{ $page }}</span></li>
                    @else
                        <li class="page-numbers"><a href="{{ $url }}">{{ $page }}</a></li>
                    @endif
                @endforeach
            @endif
        @endforeach

        <!-- Next Page Link -->
        @if ($paginator->hasMorePages())
            <li class="next page-numbers"><a href="{{ $paginator->nextPageUrl() }}" rel="next">Next</a></li>
        @endif
    </ul>

@endif

resources/views/layouts/public.blade.php
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Znews - IT news </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="{{asset('images/favicon.ico')}}">

    <!-- All css files are included here. -->
    <!-- Bootstrap fremwork main css -->
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <!-- This core.css file contents all plugings css file. -->
    <link rel="stylesheet" href="{{asset('css/core.css')}}">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="{{asset('css/shortcode/shortcodes.css')}}">
    <!-- Theme main style -->
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <!-- Responsive css -->
    <link rel="stylesheet" href="{{asset('css/responsive.css')}}">
    <!-- User style -->
    <link rel="stylesheet" href="{{asset('css/custom.css')}}">

    <link href="{{asset('plugins/Validation-Engine/validationEngine.jquery.css')}}" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" href="{{asset('AdminLTE/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">

    <!-- jQuery -->
    <script src="{{asset('AdminLTE/plugins/jquery/jquery.min.js')}}"></script>

    <!-- Modernizr JS -->
    <script src="{{asset('js/vendor/modernizr-2.8.3.min.js')}}"></script>
</head>
<body>

<!--  THEME PRELOADER AREA -->
<div id="preloader-wrapper">
    <div class="preloader-wave-effect"></div>
</div>
<!-- THEME PRELOADER AREA END -->

<!-- Body main wrapper start -->
<div class="wrapper">
    <!-- Start of header area -->
    <header  class="header-area header-wrapper bg-white clearfix">
        <!-- Start Sidebar Menu -->
        <div class="sidebar-menu">
            <div class="sidebar-menu-inner"></div>
            <span class="fa fa-remove"></span>
        </div>
        <!-- End Sidebar Menu -->

        <div class="header-middle-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-lg-4 col-sm-5 col-xs-12 header-mdh">
                        <div class="global-table">
                            <div class="global-row">
                                <div class="global-cell">
                                    <div class="logo">
                                        <a href="{{route('pages.home')}}">
                                            <img src="{{asset('images/logo/1.png')}}" alt="main logo">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div id="sticky-header" class="header-bottom-area hidden-sm hidden-xs">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="menu-wrapper  bg-theme clearfix">
                            <div class="row">
                                <div class="col-md-11">
                                    <div class="mainmenu-area">
                                        <nav class="primary-menu uppercase">
                                            <ul class="clearfix">
                                                <li><a href="{{route('pages.home')}}">Home</a></li>
                                                <li><a href="{{route('pages.news')}}">News</a></li>
                                                <li><a href="{{route('pages.contact')}}">Contact</a></li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- mobile-menu-area start -->
        <div class="mobile-menu-area hidden-md hidden-lg">
            <div class="fluid-container">
                <nav id="mobile_dropdown">
                    <ul>
                        <li><a href="{{route('pages.home')}}">Home</a></li>
                        <li><a href="{{route('pages.news')}}">News</a></li>
                        <li><a href="{{route('pages.contact')}}">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- mobile-menu-area end -->
    </header>
    <!-- End of header area -->

@yield('content')

<!-- Start footer area -->
<footer id="footer" class="footer-wrapper footer-1">
    <!-- Start footer top area -->
    <div class="footer-top-wrap ptb-70 bg-dark">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-5 hidden-sm">
                    <div class="zm-widget pr-40">
                        <h2 class="h6 zm-widget-title uppercase text-white mb-30">About Znews</h2>
                        <div class="zm-widget-content">
                            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.</p>
                            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-4 col-md-6 col-lg-3">
                    <div class="zm-widget">
                        <h2 class="h6 zm-widget-title uppercase text-white mb-30">Social Links</h2>
                        <div class="zm-widget-content">
                            <div class="zm-social-media zm-social-1">
                                <ul>
                                    <li><a href="https://www.facebook.com"><i class="fa fa-facebook"></i>Like us on Facebook</a></li>
                                    <li><a href="https://twitter.com"><i class="fa fa-twitter"></i>Tweet us on Twitter</a></li>
                                    <li><a href="https://www.pinterest.com/"><i class="fa fa-pinterest"></i>Pin us on Pinterest</a></li>
                                    <li><a href="https://www.instagram.com/"><i class="fa fa-instagram"></i>Heart us on Instagram</a></li>
                                    <li><a href="https://plus.google.com"><i class="fa fa-google-plus"></i>Share us on GooglePlus</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-6 col-lg-4">
                    <div class="zm-widget">
                        <h2 class="h6 zm-widget-title uppercase text-white mb-30">Contact</h2>
                        <!-- Start Subscribe From -->
                        <div class="zm-widget-content">
                            <div class="subscribe-form subscribe-footer">
                                <p>If you have any questions you can contact us.</p>
                                <a href="{{route('pages.contact')}}" class="contact-us"> Contact us</a>
                            </div>
                        </div>
                        <!-- End Subscribe From -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End footer top area -->
    <div class="footer-buttom bg-black ptb-15">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="zm-copyright text-center">
                        <p class="uppercase">© <?=date('Y')?> Your Company. All Rights Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- End footer area -->
</div>
<!-- Body main wrapper end -->

<!-- Placed js at the end of the document so the pages load faster -->
<!-- jquery latest version -->
<script src="{{asset('js/vendor/jquery-1.12.1.min.js')}}"></script>
<!-- Bootstrap framework js -->
<script src="{{asset('js/bootstrap.min.js')}}"></script>
<!-- All js plugins included in this file. -->
<script src="{{asset('js/owl.carousel.min.js')}}"></script>
<script src="{{asset('js/plugins.js')}}"></script>
<!-- Main js file that contents all jQuery plugins activation. -->
<script src="{{asset('js/main.js')}}"></script>

<script src="{{asset('AdminLTE/plugins/sweetalert2/sweetalert2.min.js')}}"></script>

<script src="{{asset('plugins/Validation-Engine/jquery.validationEngine.js')}}"></script>
<script src="{{asset('plugins/Validation-Engine/jquery.validationEngine-en.js')}}"></script>

<script src="{{asset('js/public.js')}}"></script>


</body>
</html>