routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@homePage')->name('pages.home');
Route::get('news', 'PagesController@newsPage')->name('pages.news');
Route::get('news/category/{category}', 'PagesController@newsPage')->name('pages.categoryNews');
Route::get('news/{news}', 'PagesController@newsDetailPage')->name('pages.detailNews');

Route::get('contact', 'PagesController@contactPage')->name('pages.contact');
Route::post('store-contact', 'PagesController@storeContact')->name('pages.storeContact');

//User login & logout
Route::get('login', 'admin\UsersController@login')->name('login');
Route::post('authenticate', 'admin\UsersController@authenticate')->name('authenticate');
Route::get('logout', 'admin\UsersController@logout')->name('logout');


Route::group(['prefix'=>'admin-panel', 'middleware'=>'auth'], function (){
    //News
    Route::post('news/select', 'admin\NewsController@selectNews')->name('news.list');
    Route::post('news/is-published/{id}', 'admin\NewsController@isPublished')->name('news.isPublished');
    Route::post('news/is-must-read/{id}', 'admin\NewsController@isMustRead')->name('news.isMustRead');
    Route::resource('news', 'admin\NewsController');

    //Category
    Route::post('category/select', 'admin\NewsCategoryController@selectCategories')->name('category.list');
    Route::resource('category', 'admin\NewsCategoryController');

    //User
    Route::get('user/profile', 'admin\UsersController@profile')->name('user.profile');
    Route::post('user/update/{user}', 'admin\UsersController@update')->name('user.update');
    Route::post('user/change-password/{user}', 'admin\UsersController@changePassword')->name('user.change-password');

    //Contact
    Route::get('contact', 'admin\ContactController@index')->name('contact.index');
    Route::post('contact/select', 'admin\ContactController@selectContact')->name('contact.list');
    Route::post('contact/is-viewed/{id}', 'admin\ContactController@isViewed')->name('contact.isViewed');

    Route::delete('contact/{id}', 'admin\ContactController@destroy')->name('contact.destroy');



});

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'news';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'alias', 'description', 'id_category', 'date_publish', 'content', 'image', 'is_published', 'is_must_read'];

    /**
     * Set primary key for table.
     *
     * @var string
     */
    protected $primaryKey = 'id_news';

    /**
     * Get category for the news.
     */
    public function category()
    {
        return $this->hasOne('App\NewsCategory', 'id_cat', 'id_category');
    }

    /**
     * Scope a query to get only published news.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeIsPublished($query)
    {
        return $query->where('is_published', 1);
    }

    /**
     * Scope a query to only include popular news.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopePopular($query)
    {
        return $query->isPublished()->orderBy('views', 'desc');
    }

    /**
     * Scope a query to get only must read news.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeMustRead($query)
    {
        return $query->isPublished()->where('is_must_read', 1);
    }
}

app/Http/Controllers/admin/NewsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Helpers\MyImage;
use App\Helpers\MyUrl;
use App\Http\Controllers\Controller;
use App\News;
use App\NewsCategory;
use Illuminate\Http\Request;

class NewsController extends Controller
{
    private $imageWidth = 900;
    private $imageHeight = 500;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin/news/index', ['activePage' => 'news']);
    }

    /**
     * @return JSON for Data table with all records
     */
    public function selectNews()
    {
        $query = News::select('id_news', 'title',  'description', 'image', 'id_category', 'created_at', 'is_must_read', 'is_published')->with('category');

        return datatables($query)
            ->order(function ($query) {
                $columns = [
                    0 => 'title',
                    5 => 'created_at'
                ];

                $dir = request()->order[0]['dir'];
                $col =  $columns[intval(request()->order[0]['column'])];

                $query->orderBy($col, $dir);
            })
            ->rawColumns(['actions', 'date_add', 'image', 'is_must_read', 'is_published', 'category', 'titleLink', 'categoryLink'])
            ->addColumn('actions', 'admin/news/partial/actions')
            ->addColumn('image', 'admin/news/partial/image')
            ->addColumn('is_must_read', 'admin/news/partial/is_must_read')
            ->addColumn('is_published', 'admin/news/partial/is_published')

            ->addColumn('date_add', function($query){
                return date('d.m.Y', strtotime($query->created_at));
            })

            ->addColumn('category', function($query){
                return $query->category['name'];
            })

            ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin/news/form', ['activePage' => 'news', 'categories' => NewsCategory::get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'        => 'required|min:3|max:100' ,
            'description'  => 'required|min:50|max:255',
            'id_category'  => 'required',
            'date_publish' => 'required',
            'content'      => 'required',
            'image'        => 'required',
        ]);

        $input = $request->all();

        $input['alias'] = MyUrl::makeSlugs($input['title']);
        $input['is_published'] = !isset($input['is_published']) ? 0 : 1;
        $input['is_must_read'] = !isset($input['is_must_read']) ? 0 : 1;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $input['image'] = uniqid() . '.' . $image->getClientOriginalExtension();

            MyImage::saveImage($image->getRealPath(), public_path('images/news/'),  $input['image'], $this->imageWidth, $this->imageHeight);
        }

        $article = new News();
        $article->fill($input);
        $article->save();

        $request->session()->flash('status', 'success');
        $request->session()->flash('message', 'News was added successfully');

        return response()->json([
            'status'  => 'success',
            'message' => 'News was added successfully',
            'redirect' => route('news.index'),
        ], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [
            'activePage' => 'news',
            'categories' => NewsCategory::get(),
            'record'     => News::findOrFail($id)
        ];

        return view('admin/news/form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title'        => 'required|min:3|max:100' ,
            'description'  => 'required|min:50|max:255',
            'id_category'  => 'required',
            'date_publish' => 'required',
            'content'      => 'required',
        ]);

        $input = $request->all();

        $input['alias'] = MyUrl::makeSlugs($input['title']);
        $input['is_published'] = !isset($input['is_published']) ? 0 : 1;
        $input['is_must_read'] = !isset($input['is_must_read']) ? 0 : 1;

        if ($request->hasFile('image')) {
            $image = $request->file('image');
            $input['image'] = uniqid() . '.' . $image->getClientOriginalExtension();

            MyImage::saveImage($image->getRealPath(), public_path('images/news/'),  $input['image'], $this->imageWidth, $this->imageHeight);

            if (isset($input['old_image']) && !empty($input['old_image'])) {
                MyImage::deleteImage(public_path('images/news/'), $input['old_image']);
            }
        }

        $article = News::findOrFail($id);
        $article->fill($input);
        $article->save();

        $request->session()->flash('status', 'success');
        $request->session()->flash('message', 'News was updated successfully');

        return response()->json([
            'status'  => 'success',
            'message' => 'News was updated successfully',
            'redirect' => route('news.index'),
        ], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news = News::findOrFail($id);

        if(isset($news['image']) && !empty($news['image'])){
            MyImage::deleteImage(public_path('images/news/'), $news['image']);
        }

        $news->delete();

        return response()->json([
            'status'  => 'success',
            'message' => 'The news has been deleted',
        ], 200);
    }

    /**
     * Make news published
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function isPublished($id)
    {
        $news = News::findOrFail($id);

        if ($news['is_published']) {
            $news->fill(['is_published' => 0]);
            $message = 'News was unpublished successfully';

        } else {
            $news->fill(['is_published' =>1]);
            $message = 'News was published successfully';
        }

        $news->update();

        return response()->json([
            'status'  => 'success',
            'message' => $message
        ], 200);
    }

    /**
     * Make news must read
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function isMustRead($id = 0)
    {
        $news = News::findOrFail($id);

        if ($news['is_must_read']) {
            $news->fill(['is_must_read' => 0]);
            $message = 'News is not "must read"';

        } else {
            $news->fill(['is_must_read' => 1]);
            $message = 'News was made "must reade"';
        }

        $news->update();

        return response()->json([
            'status'  => 'success',
            'message' => $message
        ], 200);
    }
}

resources/views/admin/news/form.blade.php
@extends('layouts.admin')

@section('content')
    <script src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>

    <div class="content-wrapper" style="min-height: 1015.13px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>News</h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Add news</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form id="news-form" action="{{!empty($record['id_news']) ? route('news.update', ['news' => $record['id_news']]) : route('news.store')}}" method="post" enctype="multipart/form-data">
                                @if (!empty($record['id_news']))
                                    <input type="hidden" name="_method" value="PUT">
                                @endif

                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" class="form-control validate[required]" id="title" name="title" value="{{!empty($record['title']) ? $record['title'] : ''}}" placeholder="Title:">
                                    </div>

                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea class="form-control validate[required]" id="description" name="description" rows="3" placeholder="Description:">{{!empty($record['description']) ? $record['description'] : ''}}</textarea>
                                    </div>

                                    <div class="form-group">
                                        <label for="id-category">Category</label>
                                        <select class="form-control" id="id-category" name="id_category">
                                            <option selected disabled>Select category</option>

                                            @if (!empty($categories))
                                                @foreach ($categories as $category)
                                                    <option value="{{$category['id_cat']}}" {{!empty($record['id_category']) && $record['id_category'] == $category['id_cat'] ? 'selected' : ''}}>
                                                        {{$category['name']}}
                                                    </option>
                                                @endforeach
                                            @endif

                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="date-publish">Date publish</label>
                                        <input type="date" class="form-control validate[required]" id="date-publish" name="date_publish" value="{{!empty($record['date_publish']) ? date('Y-m-d', strtotime($record['date_publish'])) : ''}}">
                                    </div>

                                    <div class="form-group">
                                        <label for="content">Content</label>
                                        <textarea class="form-control validate[required]" id="content" name="content" placeholder="Content:">{{!empty($record['content']) ? $record['content'] : ''}}</textarea>
                                    </div>

                                    @if (!empty($record['image']))
                                        <input type="hidden" name="old_image" value="{{$record['image']}}">
                                        <div class="form-group">
                                            <img src="{{asset('images/news/') . '/' . $record['image']}}" width="200px">
                                        </div>
                                    @endif

                                    <div class="form-group">
                                        <label for="image">Image</label>
                                        <input type="file" class="form-control {{empty($record['id_news']) ? 'validate[required]' : ''}}" id="image" name="image" placeholder="Image:">
                                    </div>

                                    <div class="form-group">
                                        <label>Published</label>
                                        <input id="published" name="is_published" type="checkbox" {{!empty($record['is_published']) && $record['is_published'] ?  'checked'  : ''}}>
                                        <label class="switch-color" for="published"></label>
                                    </div>

                                    <div class="form-group">
                                        <label>Must read</label>
                                        <input id="must-read" name="is_must_read" type="checkbox" {{!empty($record['is_must_read']) && $record['is_must_read'] ?  'checked'  : ''}}>
                                        <label class="switch-color" for="must-read"></label>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
        </section>
        <!-- /.content -->
    </div>

    <script>
        $(document).ready(function() {
            tinymce.init({
                selector: '#content',
                entity_encoding: 'raw',
                menubar: false,
                branding: false,
                height: 500,
                max_height: 700,
                min_height: 500,
                plugins: [
                    'autolink autoresize fullscreen link lists paste',
                ],
                toolbar: 'undo redo | bold italic | underline strikethrough | bullist numlist | link | fullscreen',

                link_assume_external_targets: true,
                relative_urls: false,
                image_advtab: true ,
                remove_script_host: false,
                force_br_newlines: false,
                force_p_newlines: false,
                forced_root_block: "",
                extended_valid_elements: "br",
                verify_html: false,
                valid_children: "br",
                paste_as_text: true,

            });

            var validation = $("#news-form").validationEngine('attach',{promptPosition : "bottomLeft", maxErrorsPerField: 1, validateNonVisibleFields: true, updatePromptsPosition:true});

            $('#news-form').on('submit', function (e) {
                e.preventDefault();
                if(!validation.validationEngine('validate')){
                    return false;
                }

                var formData = new FormData(this);

                $.ajax({
                    url : $(this).attr('action'),
                    type : 'POST',
                    dataType : 'JSON',
                    cache: false,
                    contentType: false,
                    processData: false,
                    data : formData,
                    success : function(response){
                        if (typeof response.redirect != 'undefined' && typeof response.redirect != null) {
                            window.location.replace(response.redirect);
                        }
                    },
                    error: function (error) {
                        onSaveRequestError(error);
                    }
                });
            });
        });

    </script>

@endsection

resources/views/admin/news/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="content-wrapper" style="min-height: 1015.13px;">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>News</h1>
                    </div>

                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">List of all news</h3>

                            <div class="card-tools">
                                <a href="{{route('news.create')}}" class="btn btn-success"><i class="fas fa-plus"></i> Add news</a>
                                <a data-fancybox data-type="ajax" data-src="{{route('category.create')}}" href="javascript:;" class="btn btn-success"><i class="fas fa-plus"></i> Add category</a>
                            </div>

                        </div>

                        @if (Session::has('status') && Session::has('message'))
                            <script>
                                $(document).ready(function() {
                                    sweetalert('{{Session::get('status')}}', 'Success', '{{Session::get('message')}}');

                                })
                            </script>
                        @endif

                        <!-- /.card-header -->
                        <div class="card-body">
                            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4"><div class="row"><div class="col-sm-12 col-md-6"></div><div class="col-sm-12 col-md-6"></div></div><div class="row"><div class="col-sm-12">
                                        <table id="categories-table" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                            <thead>
                                            <tr role="row">
                                                <th>Title</th>
                                                <th>Category</th>
                                                <th>Image</th>
                                                <th>Published</th>
                                                <th>Must read</th>
                                                <th>Date add</th>
                                                <th>Actions</th>
                                            </tr>
                                            </thead>
                                            <tbody>

                                            </tbody>

                                        </table>
                                    </div>
                                    <!-- /.card-body -->
                                </div>
                                <!-- /.card -->

                                <!-- /.card -->
                            </div>
                            <!-- /.col -->
                        </div>
                        <!-- /.row -->
                    </div>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>



    <script>
        var dt;

        $(document).ready(function() {

            dt = $('#categories-table').DataTable( {
                "processing": true,
                "serverSide": true,
                "searching": true,
                "autoWidth": false,
                responsive: true,
                stateSave: true,
                "order": [ 5, 'desc' ],
                "columnDefs": [
                    {"orderable": true, "targets": 0},
                    {"orderable": false, className: "ta-c w-200", "targets": 1},
                    {"orderable": false, className: "ta-c w-100", "targets": 2},
                    {"orderable": false, className: "ta-c w-100", "targets": 3},
                    {"orderable": false, className: "ta-c w-100", "targets": 4},
                    {"orderable": true, className: "ta-c w-100", "targets": 5},
                    {"orderable": false, className: "ta-c w-200", "targets": 6},
                ],
                "columns": [
                    { "data": "title"},
                    { "data": "category"},
                    { "data": "image"},
                    { "data": "is_published"},
                    { "data": "is_must_read"},
                    { "data": "date_add" },
                    { "data": "actions" },
                ],
                "ajax": {
                    url: "{{route('news.list')}}",
                    type: 'POST',
                }

            });
        });
    </script>

@endsection